#!/usr/bin/env ruby

require_relative 'student'
require_relative 'matchmaker'
require_relative 'file_access'

FILE = ARGV.first
INPUT_JSON = FileAccess.read FILE

students = INPUT_JSON.each_pair.map do |key, val| 
  Student.new name: key.to_s, previous_pairs: val
end

puts matcher = MatchMaker.new(students).make_pairs
FileAccess.write(FILE, matcher.to_hash)

